nome = input('Digite algo: ')
print('O tipo primitivo desse valor é' , type(nome))
print('É um número?' , nome.isnumeric())
print('É alfabetico? ' , nome.isalpha())
print('É alfanúmerico? ' , nome.isalnum())
print('Está em maiúsculas? ' , nome.isupper())
print('Está em minúsculas? ' , nome.islower())
