nome = input('Qual o seu nome: ')
print('Nome em Maiúsculas: {}'.format(nome.upper()))
print('Em minúsculas: {}'.format(nome.lower()))
print('Quantidade de letras: {}'.format(len(nome.replace(" ", ""))))
palavras = nome.split()
print('Letras do primeiro nome: {}'.format(len(palavras[0])))